import type { Comic } from "./types"

export const mockComics: Comic[] = [
  {
    id: 1,
    title: "The Last Survivor",
    author: "Alex Comics",
    image: "/post-apocalyptic-comic-illustration.jpg",
    likes: 2341,
    comments: 156,
    description: "A gripping tale of survival in a dystopian world",
  },
  {
    id: 2,
    title: "Midnight Mystery",
    author: "Luna Studio",
    image: "/mystery-thriller-comic-art.jpg",
    likes: 1890,
    comments: 234,
    description: "A thrilling mystery that unfolds in the darkness",
  },
  {
    id: 3,
    title: "Urban Dreams",
    author: "City Tales",
    image: "/urban-sci-fi-cyberpunk-comic.jpg",
    likes: 3124,
    comments: 412,
    description: "Futuristic stories from the heart of the city",
  },
  {
    id: 4,
    title: "Legends of Old",
    author: "Classic Comics",
    image: "/fantasy-medieval-legend-comic.jpg",
    likes: 2567,
    comments: 189,
    description: "Ancient legends reimagined for modern times",
  },
  {
    id: 5,
    title: "Cosmic Adventures",
    author: "Galaxy Press",
    image: "/space-adventure-sci-fi-comic.jpg",
    likes: 4012,
    comments: 678,
    description: "Journey through the stars with amazing tales",
  },
  {
    id: 6,
    title: "Silent Shadows",
    author: "Dark Comics",
    image: "/noir-dark-mystery-comic.jpg",
    likes: 1756,
    comments: 123,
    description: "Where darkness hides untold secrets",
  },
]
